import React, { useState, useEffect, useRef } from 'react';
import { Bot, Play, Terminal, Zap, CheckCircle2, Loader2, Database, Shield, HeartHandshake, Activity } from 'lucide-react';
import { runScenarioAgent, runUXAgent, runPrivacyAgent, runDataIntegrityCheck } from '../services/agentService';
import { useEntriesStore } from '../hooks/useEntriesStore';
import { useSettingsStore } from '../hooks/useSettingsStore';
import { useAppContext } from '../context/AppContext';

type TestStep = 'IDLE' | 'INTEGRITY' | 'STRESS' | 'PRIVACY' | 'FAIRNESS' | 'COMPLETE';
type IconType = React.ComponentType<{ size?: number; className?: string }>;

const AgentLab: React.FC = () => {
  const { entries, addEntries } = useEntriesStore();
  const { settings } = useSettingsStore();
  const { users } = useAppContext();
  const [logs, setLogs] = useState<string[]>(['> KinCircle Test Suite initialized.', '> Auto-start sequence initiated...']);
  const [testStatus, setTestStatus] = useState<TestStep>('IDLE');
  const [uxFeedback, setUxFeedback] = useState<string | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  const hasRun = useRef(false);

  // Auto-scroll logs
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [logs]);

  // Auto-Run on Mount
  useEffect(() => {
    if (!hasRun.current) {
      hasRun.current = true;
      runDiagnostics();
    }
  }, []);

  const addLog = (msg: string) => setLogs(prev => [...prev, `> ${msg}`]);

  const runDiagnostics = async () => {
    if (testStatus !== 'IDLE' && testStatus !== 'COMPLETE') return;

    setTestStatus('INTEGRITY');
    setLogs(['> STARTING FULL SYSTEM DIAGNOSTIC...', '-----------------------------------']);
    setUxFeedback(null);

    // 1. Data Integrity
    addLog('[Unit Test] Checking ledger data integrity...');
    await new Promise(r => setTimeout(r, 800)); // Visual delay
    const integrity = await runDataIntegrityCheck(entries, users);
    if (integrity.passed) {
      addLog('[Unit Test] PASS: Data structure valid.');
    } else {
      addLog(`[Unit Test] FAIL: Found ${integrity.issues.length} issues.`);
      integrity.issues.forEach(i => addLog(`  - ${i}`));
    }

    // 2. Stress Test (Scenario Injection)
    setTestStatus('STRESS');
    addLog('[Stress Test] Injecting complex "Medical Emergency" scenario...');
    try {
      // Use the first user as the "actor" for the scenario
      const newEntries = await runScenarioAgent("Unexpected ER Visit and Follow-up Care", users[0].id);
      if (newEntries && newEntries.length > 0) {
        addEntries(newEntries);
        addLog(`[Stress Test] PASS: Injected ${newEntries.length} new records successfully.`);
      } else {
        addLog('[Stress Test] WARN: No entries generated by Agent.');
      }
    } catch (e) {
      addLog('[Stress Test] FAIL: Simulation agent error.');
    }

    // 3. Privacy Audit
    setTestStatus('PRIVACY');
    addLog('[Compliance] Auditing PII exposure...');
    await new Promise(r => setTimeout(r, 800));
    const privacy = await runPrivacyAgent(entries, settings);
    if (!settings.privacyMode) {
      addLog('[Compliance] WARN: Privacy Mode is DISABLED. PII is visible.');
    } else if (privacy.safe) {
      addLog('[Compliance] PASS: No PII detected in descriptions.');
    } else {
      addLog(`[Compliance] FAIL: ${privacy.leakedEntries.length} records expose patient data.`);
    }

    // 4. Fairness Analysis
    setTestStatus('FAIRNESS');
    addLog('[UX/AI] Analyzing sibling equity balance...');
    const feedback = await runUXAgent(entries, users, settings);
    setUxFeedback(feedback);
    addLog('[UX/AI] Analysis received.');

    setTestStatus('COMPLETE');
    addLog('-----------------------------------');
    addLog('> DIAGNOSTIC SEQUENCE COMPLETE.');
  };

  const StepIndicator = ({ step, current, label, icon: Icon }: { step: TestStep, current: TestStep, label: string, icon: IconType }) => {
    const steps = ['IDLE', 'INTEGRITY', 'STRESS', 'PRIVACY', 'FAIRNESS', 'COMPLETE'];
    const stepIdx = steps.indexOf(step);
    const currentIdx = steps.indexOf(current);

    let statusClasses = 'text-slate-400 bg-slate-50 border-slate-200';
    if (current === step) {
      // Active
      statusClasses = 'text-teal-600 bg-teal-50 border-teal-200 ring-1 ring-teal-300 shadow-sm scale-105';
    } else if (currentIdx > stepIdx) {
      // Passed
      statusClasses = 'text-green-600 bg-green-50 border-green-200';
    }

    return (
      <div className={`flex items-center space-x-3 p-3 rounded-lg border transition-all duration-300 ${statusClasses}`}>
        <div className={`p-2 rounded-full ${current === step ? 'bg-white shadow-sm' : 'bg-transparent'}`}>
          {currentIdx > stepIdx ? <CheckCircle2 size={20} /> : <Icon size={20} className={current === step ? 'animate-pulse' : ''} />}
        </div>
        <span className="font-medium text-sm">{label}</span>
      </div>
    );
  };

  return (
    <div className="space-y-6 animate-fade-in h-[calc(100vh-8rem)] flex flex-col">
      <header className="flex items-center space-x-3 mb-2 flex-shrink-0">
        <div className="p-3 bg-indigo-900 text-white rounded-lg">
          <Bot size={24} />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-slate-900">KinCircle Auto-Diagnostics</h1>
          <p className="text-slate-500">Automated system verification and stress testing.</p>
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 min-h-0">
        {/* Left Column: Test Controls */}
        <div className="lg:col-span-1 space-y-4 overflow-y-auto pr-2">

          {/* Main Action */}
          <div className="bg-white p-6 rounded-xl border border-indigo-100 shadow-sm">
            <h3 className="font-semibold text-indigo-900 mb-2 flex items-center">
              <Zap size={18} className="mr-2 fill-indigo-100" />
              Test Suite Status
            </h3>
            <p className="text-sm text-slate-600 mb-6">
              Tests are running automatically to verify data integrity, privacy compliance, and AI generation capabilities.
            </p>
            <button
              onClick={runDiagnostics}
              disabled={testStatus !== 'IDLE' && testStatus !== 'COMPLETE'}
              className="btn-primary w-full py-3 shadow-md shadow-teal-200 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {testStatus !== 'IDLE' && testStatus !== 'COMPLETE' ? (
                <>
                  <Loader2 size={18} className="animate-spin" />
                  <span>Running Tests...</span>
                </>
              ) : (
                <>
                  <Play size={18} />
                  <span>Re-Run Diagnostics</span>
                </>
              )}
            </button>
          </div>

          {/* Progress Indicators */}
          <div className="space-y-2">
            <StepIndicator step="INTEGRITY" current={testStatus} label="Data Integrity Check" icon={Database} />
            <StepIndicator step="STRESS" current={testStatus} label="Scenario Injection" icon={Activity} />
            <StepIndicator step="PRIVACY" current={testStatus} label="Privacy Compliance" icon={Shield} />
            <StepIndicator step="FAIRNESS" current={testStatus} label="Equity Analysis" icon={HeartHandshake} />
          </div>

          {/* Result Card */}
          {uxFeedback && (
            <div className="bg-emerald-50 border border-emerald-100 p-4 rounded-xl animate-slide-up">
              <div className="flex items-center space-x-2 mb-2 text-emerald-800">
                <CheckCircle2 size={18} />
                <span className="font-bold">Final Verdict</span>
              </div>
              <p className="text-sm text-emerald-900 italic">&ldquo;{uxFeedback}&rdquo;</p>
            </div>
          )}
        </div>

        {/* Right Column: Terminal Output */}
        <div className="lg:col-span-2 flex flex-col bg-slate-950 rounded-xl overflow-hidden shadow-2xl border border-slate-800">
          <div className="bg-slate-900 p-3 flex items-center justify-between border-b border-slate-800">
            <div className="flex items-center space-x-2">
              <Terminal size={16} className="text-slate-400" />
              <span className="text-xs font-mono text-slate-300">test_runner_output.log</span>
            </div>
            <div className="flex space-x-1.5">
              <div className="w-2.5 h-2.5 rounded-full bg-red-500/50"></div>
              <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/50"></div>
              <div className="w-2.5 h-2.5 rounded-full bg-green-500/50"></div>
            </div>
          </div>

          <div
            ref={scrollRef}
            className="flex-1 p-4 font-mono text-xs md:text-sm text-slate-300 overflow-y-auto space-y-1.5"
          >
            {logs.map((log, i) => {
              const isError = log.includes('FAIL');
              const isWarn = log.includes('WARN');
              const isPass = log.includes('PASS');
              const isHeader = log.includes('STARTING') || log.includes('COMPLETE');

              let colorClass = 'text-slate-300';
              if (isError) colorClass = 'text-red-400 font-bold';
              if (isWarn) colorClass = 'text-yellow-400';
              if (isPass) colorClass = 'text-green-400';
              if (isHeader) colorClass = 'text-blue-400 font-bold';

              return (
                <div key={i} className={`${colorClass} break-words`}>
                  {log}
                </div>
              );
            })}
            {(testStatus !== 'IDLE' && testStatus !== 'COMPLETE') && (
              <div className="animate-pulse text-slate-500">_</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default AgentLab;
